# Pytorch 


In [3]:
import torch


In [2]:
torch.cuda.is_available()

False

In [5]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('./Iris.csv')
df


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
df.shape #xem số hàng và số cột

(150, 6)

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
Y = le.fit_transform(df["Species"].values)

#Chia dữ liệu với test size = 20%

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)


In [9]:
len(y_train) , len(y_test), len(x_train), len(x_test)

(120, 30, 120, 30)

In [10]:
Labels, counts = y_train.unique(return_counts=True)
print(Labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
#Tính đạo hàm bằng Pytorch

#Cho y = 2x^4 + x^3 + 3x^2 + 5x + 1

#Tính y' 

In [11]:
import torch

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [17]:
#Định nghĩa hàm 
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [18]:
y.grad_fn

In [19]:
# Thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [ ]:
# 8x^3 + 3x^2 + 6x + 5 
x.grad

tensor(93.)

In [ ]:
#BTVN 
# Cho y = 5x^5 + 6x^3 - 3x + 1 
# Cho biết độ dốc của đa thức trên ở điểm nào

In [ ]:
import torch

# Khởi tạo x
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số
y = 5*x**5 + 6*x**3 - 3*x + 1

# Tính toán gradient
y.backward()

print(f"Độ dốc của hàm số tại x = 2 là: {x.grad}")


Độ dốc của hàm số tại x = 2 là: 469.0


In [ ]:
#BTVN 02
#Tạo một tensor ban đầu có giá trị là 2
#Định nghĩa hàm số và tính gradient
#y =x^3 + 2x^2 + 5x + 1
# Hãy tính dy/dx tại giá trị của x
# Dùng phương pháp Gradient Descent với Learning rate alpha = 0.1 để cập nhật giá trị x trong vòng 10 vòng lặp

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
learning_rate = 0.1

for epoch in range(10):
    y = x**3 + 2*x**2 + 5*x + 1
    # Tính gradient
    y.backward()
    # Cập nhật x
    with torch.no_grad():
        x -= learning_rate * x.grad

        x.grad.zero_()
        
    print(f"Vòng lặp {epoch+1}: x = {x.item():.4f}, y = {y.item():.4f}")

Vòng lặp 1: x = -0.5000, y = 27.0000
Vòng lặp 2: x = -0.8750, y = -1.1250
Vòng lặp 3: x = -1.2547, y = -2.5137
Vòng lặp 4: x = -1.7251, y = -4.1001
Vòng lặp 5: x = -2.4278, y = -6.8073
Vòng lặp 6: x = -3.7250, y = -13.6609
Vòng lặp 7: x = -6.8977, y = -41.5604
Vòng lặp 8: x = -18.9120, y = -266.5102
Vòng lặp 9: x = -119.1464, y = -6142.3750
Vòng lặp 10: x = -4330.7476, y = -1663589.5000


## BTVN 03
Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 tới 10) và y là số điểm được tính theo công thức y = 3x + 5 + Noise
Với Noise là một giá tị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requirers_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
5. Lập lại quá trình trên trong 100 vòng lập để xem sự hội tụ của mô hình

In [ ]:
import torch

# 1. Khởi tạo dữ liệu giả lập
torch.manual_seed(100)
X = torch.randint(1, 11, (100, 1)).float()
noise = torch.randn(100, 1) * 0.5
Y = 3 * X + 5 + noise

# Khởi tạo w và b ngẫu nhiên
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
alpha = 0.01

#5 Lặp 100 lần
for epoch in range(100):
    # Dự đoán
    y_pred = X * w + b
    
    #2 Tính MSE 
    loss = torch.mean((y_pred - Y)**2)
    
    #3 Tính Gradient
    loss.backward()
    
    #4 Cập nhật tham số
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
        
        # Xóa gradient
        w.grad.zero_()
        b.grad.zero_()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

Epoch 10: Loss = 5.6801, w = 3.7158, b = -0.0700
Epoch 20: Loss = 5.2426, w = 3.6868, b = 0.1365
Epoch 30: Loss = 4.8405, w = 3.6590, b = 0.3344
Epoch 40: Loss = 4.4709, w = 3.6324, b = 0.5242
Epoch 50: Loss = 4.1313, w = 3.6068, b = 0.7061
Epoch 60: Loss = 3.8191, w = 3.5823, b = 0.8805
Epoch 70: Loss = 3.5323, w = 3.5588, b = 1.0477
Epoch 80: Loss = 3.2686, w = 3.5363, b = 1.2079
Epoch 90: Loss = 3.0263, w = 3.5147, b = 1.3616
Epoch 100: Loss = 2.8036, w = 3.4941, b = 1.5089


In [21]:
#Pytorch with Tensor

import torch
import numpy as np

In [22]:
torch.__version__

'2.9.1+cpu'

In [23]:
#Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [24]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [25]:
print(x.dtype)

torch.int64


In [26]:
print(x.type())

torch.LongTensor


In [28]:
arr2 = np.arange(0., 12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [32]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [37]:
#Copy and sharing

x = torch.from_numpy(arr)
print(x)

tensor([99,  1,  2,  3,  4])


In [34]:
arr[0] = 99
print(x) 

tensor([99,  2,  3,  4,  5])


In [35]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[0] = 99
print

tensor([99,  1,  2,  3,  4])


## BTVN 04
Giải thích 2 trường hợp trên (một cái có thể thay thế được 99, một cái không)

## BTVn04 - Bài làm
Trong trường hợp 1 khi dùng hàm torch.from_numpy(arr) với mục đích là tạo ra một Tensor đống vai trò như một lớp vỏ bao bọc vùng bộ nhớ của mảng Numpy. Khác với trường hợp 2 khi dùng hàm torch.tensor(arr) là tạo một vùng bộ nhớ hoàn toàn mới và sao chép toàn bộ giá trị từ mảng Numpy sang vùng bộ nhớ đó

Nên khi thực hiện arr[0] 99 với 2 trường hợp cho ra kết quả khác nhau, với trường hợp 1 là đang dùng chung một bộ nhớ, trường hợp 2 là đang dùng tensor cũ.


## BTVN 05
Bạn giúp thầy tạo tensor với
1. empty 
2. zeros
3. ones
4. random
5. Reshape với view và view as

In [ ]:
# 1. Empty 
t_empty = torch.empty(2, 3)

# 2. Zeros 
t_zeros = torch.zeros(2, 3)

# 3. Ones 
t_ones = torch.ones(2, 3)

# 4. Random 
t_rand = torch.rand(2, 3)

# 5. Reshape với view và view_as
x = torch.arange(10) 
x_view = x.view(2, 5) # Chuyển thành 2 hàng 5 cột

y = torch.zeros(5, 2)
x_view_as = x.view_as(y) 

print(f"View:{x_view}")
print(f"View_as:{x_view_as}")

View:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
View_as:
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
