# DEEP LEARNING 
## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# NUMPY 

In [1]:
# Numpy là thư viện kiểu list
# Vì:
#+ numpy nhanh
#+ Có nhiều hàm tích hợp
#+ Dễ sử dụng cho AI

# để sử numpy thì : pip install numpy

import numpy as np

In [3]:
#thử tạo 1 list

python_list = [1,2,3,4,5]

#chuyển đổi danh sách trên thành numpy list
numpy_array = np.array([1,2,3,4,5])
type(numpy_array)


numpy.ndarray

In [4]:
# list trong python có thể hổ trợ nhiều loại dữ liễu trong list
my_list = [1, "chào", 2.0, True]

In [12]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [13]:
#Chuyển đổi kiểu dữ liệu
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [15]:
# accessing và indexing

x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [ ]:
# lấy số 4
x[3]

np.int64(4)

In [ ]:
#lấy nhiều hơn 1 phần tử
#công thức [start : and : step]

#Lấy 1 2 3
x[0:3]

array([1, 3])

In [ ]:
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [23]:
x[2:]

array([3, 4, 5, 6, 7, 8])

In [24]:
x[(x>2) & (x< 9)]

array([3, 4, 5, 6, 7, 8])

In [25]:
#Test 
x[2:-1]

array([3, 4, 5, 6, 7])

In [28]:
x[2:5:2]


array([3, 5])

In [29]:
#Đặt danh sách các index muốn truy cập
x[[2,4]]


array([3, 5])

In [30]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#lấy số 2
np_list[0, 1]


np.int64(2)

In [35]:
np_list[2,1]

np.int64(6)

In [37]:
np_list[1:, :]


array([[3, 4],
       [5, 6]])

In [38]:
np_list[[1, 2]]


array([[3, 4],
       [5, 6]])

In [39]:
np_list[1:].reshape(-1)


array([3, 4, 5, 6])

In [44]:
np_list[np.arange(len(np_list)) >= 1]


array([[3, 4],
       [5, 6]])

In [45]:
np_list.take([2,3,4,5])


array([3, 4, 5, 6])

In [46]:
np_list[np.arange(len(np_list)) >= 1]

array([[3, 4],
       [5, 6]])

In [41]:
np_list[1:].flatten()


array([3, 4, 5, 6])

In [42]:
np_list[1:].ravel()


array([3, 4, 5, 6])

In [47]:
np_list[-2:]


array([[3, 4],
       [5, 6]])

In [48]:
#Lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [ ]:
#Lấy 1 và 5 theo 2 cách 
np_list[: : 2,0]

array([1, 5])

In [ ]:
np_list[[0,2] ,0]

array([1, 5])

In [52]:
x = [
    [1,2,3,4], 
    [5,6,7,8], 
    [9,10,11,12], 
    [13,14,15,16]
    ]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
#Lấy 2 6 10 14

np_list[: ,1]

array([ 2,  6, 10, 14])

In [65]:
#Lấy 7 và 11
np_list[[1,2],2]

array([ 7, 11])

In [67]:
np_list[[0, 1, 2], [3, 2, 1]]


array([ 4,  7, 10])

In [ ]:
#Lấy 16 15 14 13

np_list[-1, ::-1]


array([16, 15, 14, 13])

In [ ]:
# BTVN 01

#Cho ma trận bằng = [[99,99,99], 
#                    [99,99,99], 
#                    [99,99,99]]
# Hãy tưởng tượng ô 99 trống
# Giả sử 1 là x
# Giả sử 0 là o

# Lấy đầu vào từ phía x và phía o luân phiên
# Nếu đầu vào từ phía x là (0,0) thì 
# ma trận sẽ trở thành [[x,99,99], 
#                       [99,99,99], 
#                       [99,99,99]]


# Nếu đầu vào từ phía o cũng là (0,0) thì 
#  + Thông báo nhập lại
#  + Nếu không thì điền vào ma trận

# Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi


import numpy as np

# Khởi tạo ma trận
board = np.full((3, 3), 99, dtype=object)

def play_step(row, col, player):
    if board[row, col] == 99:
        board[row, col] = player
        print(f"Người chơi {player} đánh vào ({row}, {col})")
        print(board)
    else:
        print("Ô này có người đánh rồi!")



play_step(0, 0, 'x')  # Lượt 1: x đánh (0,0)
play_step(1, 1, 'o')  # Lượt 2: o đánh (1,1)
play_step(0, 1, 'x')  # Lượt 3: x đánh (0,1)

Người chơi x đánh vào (0, 0)
[['x' 99 99]
 [99 99 99]
 [99 99 99]]
Người chơi o đánh vào (1, 1)
[['x' 99 99]
 [99 'o' 99]
 [99 99 99]]
Người chơi x đánh vào (0, 1)
[['x' 'x' 99]
 [99 'o' 99]
 [99 99 99]]


In [101]:
# BTVN 02

# Cho y = [[1,2,3],
#          [4,5,6],
#          [7,8,9]]


# Lấy 2 5
# Lấy 3,4
# Lấy 9, 6, 3

list = [[1,2,3] , 
        [4,5,6], 
        [7,8,9]]
list = np.array(list)
list
# Lấy 4 5 6
list[1]
list[-2]

# Lấy 3,4
list[[0,1], [2,0]]

# Lấy 9, 6, 3
list[[2,1,0], 2]



array([9, 6, 3])

In [ ]:
# BTVN 03

# Cho x = [1,2,3,4,5,6,7,8,9,10]
x = [1,2,3,4,5,6,7,8,9,10]

# 1. Xuất giá trị chẵn dùng if 
even_if = [i for i in x if i % 2 == 0]
print("Chẵn (if):", even_if)

# 2. Xuất giá trị chẵn dùng List Comprehension 
even_list = [i for i in x if i % 2 == 0]
print("Chẵn:", even_list)

Chẵn (if): [2, 4, 6, 8, 10]
Chẵn (NumPy Indexing): [2, 4, 6, 8, 10]


In [81]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np_x % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [88]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
idx = [ True, True,  True, False,  True, True,  True, False,  True,
       False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [91]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
cond1= np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# BTVN 04

# Tạo một mảng numpy có kích thước 150 x 5. Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương, điểm trung bình
# Tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y 

# Tách X thành X_train và X_test trong đó X_train chứa 70% dữ liệu
# Tách Y thành Y_train và Y_test trong đó Y_train chứa 70% dữ liệu
# Tạo 10 tập dữ liệu X_train không chồng chéo nhau


# Tạo mảng ngẫu nhiên 
data = np.random.rand(150, 5)

# 1. Tách mảng thành X (4 cột đầu) và y (cột cuối)
X = data[:, :4]
y = data[:, 4]

# 2. Tách X_train, X_test (70% - 30%)
split_idx = int(0.7 * len(X))

X_train = X[:split_idx]
X_test = X[split_idx:]

# 3. Tách Y_train, Y_test
y_train = y[:split_idx]
y_test = y[split_idx:]

print(f"Kích thước X_train: {X_train.shape}, X_test: {X_test.shape}")

# 4. Tạo 10 tập dữ liệu X_train không chồng chéo
X_train_subsets = np.array_split(X_train, 10)
print(f"Số lượng tập con: {len(X_train_subsets)}, mỗi tập có shape: {X_train_subsets[0].shape}")

Kích thước X_train: (105, 4), X_test: (45, 4)
Số lượng tập con: 10, mỗi tập có shape: (11, 4)
